universe = vanilla
executable = /home/ethan.payne/projects/GWPhotonCounting/projects/PM_EOS/hierarchical_EOS/testing/injection_submit.sh
log = /home/ethan.payne/projects/GWPhotonCounting/projects/PM_EOS/hierarchical_EOS/testing/logs/$(id).log
error = /home/ethan.payne/projects/GWPhotonCounting/projects/PM_EOS/hierarchical_EOS/testing/logs/$(id).err
output = /home/ethan.payne/projects/GWPhotonCounting/projects/PM_EOS/hierarchical_EOS/testing/logs/$(id).out
arguments = $(id)
accounting_group = ligo.dev.o4.cbc.pe.lalinference
notification = error
request_memory = 8192
request_disk = 1
getenv = true
max_retries = 5
queue 1
